### ISSUE TITLE
Cannot find module 'unplugin-vue-define-options/vite' or its corresponding type declarations.

### ISSUE THREAD

**Issue by zynth17** [sxzz/unplugin-vue-macros#266]
### Describe the bug

i got an error while using only vue define options on vite config
Cannot find module 'unplugin-vue-define-options/vite' or its corresponding type declarations. 

<img width="853" alt="image" src="https://user-images.githubusercontent.com/45350572/218361053-d9900f44-3552-4436-95d7-23625b1504e3.png">

### Reproduction

 https://stackblitz.com/edit/vitejs-vite-nkxmdt?file=vite.config.ts&terminal=dev

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 58.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Brave Browser: 108.1.46.153
    Firefox Developer Edition: 110.0
    Safari: 16.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Duplicate of #257

**Comment by pany-ang** [comment]
1. 如果 ts 版本小于 5，那么出现这个告警的原因应该是最新版 vscode，测试后发现好像 vscode 1.74 以及更早的版本不会出现该告警（这种情况下，你几乎只能忍着这个警告不管，其他措施会导致 build 报错，或者降低你的 vscode 版本）

2. 如果 ts 版本大于 5，那么你可以选择将 moduleResolution 配置为 bundler，但是这样的话，其他依赖（比如 Element Plus）可能就会疯狂报错（等待官方修复这个问题中...）。你也可以选择“// @ts-expect-error”来忽略这个错误，忽略后能正常 build

3. ts 小于 5，并且又是最新版 vscode 时最难受，几乎处理不了这个报错

所以总结一下，如果 ts 小于 5，那么就不要去管它，issues 里面的别人给的方法，几乎都会导致 build 出错。如果 ts 大于 5，那么就暂时用“// @ts-expect-error”来忽略这个错误，这样能正常 build

1. If the TS version is less than 5, then the reason for this alarm should be the latest version of VSCODE, after testing, it seems that VSCODE 1.74 and earlier versions will not appear this alarm (in this case, you can almost only endure this warning, other measures will cause build errors, or reduce your VSCODE version)

2. If the ts version is greater than 5, then you can choose to configure moduleResolution as a bundler, but in this case, other dependencies (such as Element Plus) may report crazy errors (waiting for the official fix of this problem...). ）。 You can also select "// @ts-expect-error" to ignore this error, and it will build normally after ignoring it

3. TS is less than 5, and it is the most uncomfortable when the latest version of VSCODE, and it is almost impossible to handle this error

So to sum up, if ts is less than 5, then don't care about it, the methods given by others in issues will almost always cause build errors. If ts is greater than 5, then temporarily ignore this error with "// @ts-expect-error", so that it can build normally

**Comment by Lzhij** [comment]
> 1. 如果 ts 版本小于 5，那么出现这个告警的原因应该是最新版 vscode，测试后发现好像 vscode 1.74 以及更早的版本不会出现该告警（这种情况下，你几乎只能忍着这个警告不管，其他措施会导致 build 报错，或者降低你的 vscode 版本）
> 2. 如果 ts 版本大于 5，那么你可以选择将 moduleResolution 配置为 bundler，但是这样的话，其他依赖（比如 Element Plus）可能就会疯狂报错（等待官方修复这个问题中...）。你也可以选择“// @ts-expect-error”来忽略这个错误，忽略后能正常 build
> 3. ts 小于 5，并且又是最新版 vscode 时最难受，几乎处理不了这个报错
> 
> 所以总结一下，如果 ts 小于 5，那么就不要去管它，issues 里面的别人给的方法，几乎都会导致 build 出错。如果 ts 大于 5，那么就暂时用“// @ts-expect-error”来忽略这个错误，这样能正常 build
> 
> 1. 如果 TS 版本小于 5，那么出现此报警的原因应该是最新版本的 VSCODE，经过测试，似乎 VSCODE 1.74 及更早版本不会出现此报警（在这种情况下，您几乎只能忍受此警告，其他措施会导致构建错误，或者降低您的 VSCODE 版本）
> 2. 如果 ts 版本大于 5，那么您可以选择将 moduleResolution 配置为捆绑器，但在这种情况下，其他依赖项（例如 Element Plus）可能会报告疯狂的错误（等待此问题的官方修复......）。你也可以选择“//”忽略这个错误，忽略后会正常构建
> 3. TS小于5，最新版本VSCODE时最难受，几乎不可能处理这个错误
> 
> 所以总结一下，如果ts小于5，那就不用在意了，别人在问题中给出的方法几乎总是会导致构建错误。如果 ts 大于 5，则暂时用 “// ” 忽略此错误，以便它可以正常构建
谢谢大佬
